name: Publish to PyPI.org
on:
  push:
    branches:
      - main
  release:
    types: [published]
jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          .github/scripts/version.py
          git config user.name r3ap3rpy
          git config user.email r3ap3rpy@gmail.com 
          git add .
          git commit -m "Version bumped!"
          git push
  buldAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          verify-metadata: false
